### PR TITLE
Small typo in README

### PR DESCRIPTION
**Pull request by lancew**

### CODE REVIEW

**Comment by melezhik** [comment]
Thanks alot @lancew !

**Comment by lancew** [comment]
Considering using swat in $dayjob; so browsing the documentation. :-)

**Comment by melezhik** [comment]
Oh, great! Let me know if anything you need!

Yeah, you know I am not a native speaker, so you are welcome to adjust my docs!

**Comment by melezhik** [comment]
FIY, this intro could be also helpful in understanding swat - https://github.com/melezhik/swat/blob/master/intro.md , perlblogs posts as well :)

**Pull request merged**
