### PR TITLE
s/it's/its/ where appropriate.

### PR DESCRIPTION
**Pull request by rbowen**

### CODE REVIEW

**Comment by melezhik** [comment]
Thanks!

**Comment by melezhik** [comment]
by the way, do you use swat? :smile:

**Comment by rbowen** [comment]
On 07/13/2016 03:12 PM, Alexey wrote:

> by the way, do you use swat? 😄

Some colleagues pointed me to it today, and I'm planning to give it a
spin this evening.

--Rich

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/melezhik/swat/pull/23#issuecomment-232457000, or
> mute the thread
> https://github.com/notifications/unsubscribe/AAPnQDxrmIj_sy4nuxSHDOXVyO2Qa92Sks5qVTiYgaJpZM4JLsNJ.

## 

Rich Bowen - rbowen@rcbowen.com - @rbowen
http://apachecon.com/ - @apachecon

**Comment by melezhik** [comment]
well, sounds good. I have not developed this project for the last time. But let me know if it become interesting for you or in case you have any further questions, ideas, issues ...

**Pull request merged**
